class ZBP_R_LIB_LIBRO_05 definition
 PUBLIC
  ABSTRACT
  FINAL
  FOR BEHAVIOR OF zr_lib_libro_05.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zbp_r_lib_libro_05 IMPLEMENTATION.

ENDCLASS.
