CLASS zcl_estructura_ecd DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  INTERFACES if_oo_adt_classrun.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_estructura_ecd IMPLEMENTATION.
 METHOD if_oo_adt_classrun~main.
 DATA LV_VAR1 TYPE I.


"FORMA 1

 TYPES:BEGIN OF TY_CLIENTE,
       NOMBRE TYPE STRING,
       EDAD TYPE I,
       CORREO TYPE STRING,
       TELEFONO TYPE STRING,
       END OF TY_CLIENTE.


       DATA LS_CLIENTE TYPE TY_CLIENTE.

       LS_CLIENTE-NOMBRE = 'JUAN'.
       LS_CLIENTE-edad = 40.
       LS_CLIENTE-correo = 'HOLA@SAP'.
       LS_CLIENTE-telefono = '+34111111'.


        out->write( lS_CLIENTE ).

"FORMA 2

     DATA(LS_VAR2) = VALUE  TY_CLIENTE(  NOMBRE = 'EMILIA ' EDAD = 32 ).
      out->write( lS_VAR2 ).


*FORMA 3

DATA: BEGIN OF LS_EMPLEADO2,
       NOMBRE TYPE STRING,
       EDAD TYPE I,
       CORREO TYPE /DMO/EMAIL_ADDRESS,
       END OF LS_EMPLEADO2.

        out->write( lS_EMPLEADO2 ).

 "ESTRUCTURA ANIDADA.

 DATA: BEGIN OF LS_EMPLEADO,

  BEGIN OF INFO,
    ID TYPE I VALUE 1234,
    NOMBRE TYPE STRING VALUE 'EMILIA',
  END OF INFO,


  BEGIN OF DIRECCION,
    CIUDAD TYPE STRING VALUE 'SEVILLA',
    PAIS TYPE STRING VALUE 'ESPAÑA',
  END OF DIRECCION,


 END OF LS_EMPLEADO.



ENDMETHOD.

ENDCLASS.
